version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PLATFORM=telegram
    image: duty_schedule_bot_local
    volumes:
      - .:/app
    command: tg-bot
    environment:
      TELEGRAM_TOKEN: "FILL ME"
    depends_on:
      - redis
  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PLATFORM=telegram
    image: duty_schedule_bot_local
    volumes:
      - .:/app
    command: tg-scheduler
    environment:
      TELEGRAM_TOKEN: "FILL ME"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
